# Generated by Django 4.2.2 on 2023-06-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blumoclientAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
